repos:
  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix]
        files: virtuallab
      - id: ruff-format
        files: virtuallab